# cluster parameters
clustering:
  clustering_method: alpine # alpine or dbscan or hdbscan
  epsilon: 2.5
  min_cluster_size: 25
  num_clusters: 100

# alpine parameters
alpine:
  bbox_source: dataset # dataset or web
  margin: 1.3
  neighbours: 32

# let-it-flow parameters
let_it_flow:
  K: 16
  d_thre: 0.03
  dist_w: 2.
  eps: 0.3
  iters: 1500
  lr: 0.03
  passing_ids: True
  min_samples: 1
  sc_w: 1.
  temporal_range: 2
  trunc_dist: 0.5

# association parameters
association:
  max_dist: 3.5

nuscenes:
  fore_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  config_downstream: ScaLR/configs/downstream/nuscenes/WI_768_linprob.yaml

kitti:
  fore_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  config_downstream: ScaLR/configs/downstream/semantic_kitti/WI_768_linprob.yaml
