pone:
  colors: [
      [0, 0, 255], # car
      [0, 255, 255], # bicycle
      [255, 255, 0], # motorcycle
      [255, 192, 203], # truck
      [128, 0, 128], # other-vehicle
      [255, 0, 255], # person
      [0, 128, 128], # bicyclist
      [128, 128, 0], # motorcyclist
      [128, 128, 128], # road
      [255, 192, 203], # parking
      [211, 211, 211], # sidewalk
      [165, 42, 42], # other-ground
      [255, 215, 0], # building
      [255, 0, 0], # fence
      [173, 255, 47], # vegetation
      [160, 82, 45], # trunk
      [34, 139, 34], # terrain
      [112, 128, 144], # pole
      [220, 20, 60], # traffic-sign
    ]
  names:
    [
      "car",
      "bicycle",
      "motorcyle",
      "truck",
      "other vehicle",
      "person",
      "bicyclist",
      "motorcyclist",
      "road",
      "parking",
      "sidewalk",
      "other ground",
      "building",
      "fence",
      "vegetation",
      "trunk",
      "terrain",
      "pole",
      "traffic sign",
    ]
  fps: 10

nuscenes:
  colors: [
      [255, 0, 0], # barrier
      [0, 255, 255], # bicycle
      [255, 255, 0], # bus
      [0, 0, 255], # car
      [128, 0, 128], # construction_vehicle
      [255, 255, 0], # motorcycle
      [255, 0, 255], # pedestrian
      [220, 20, 60], # traffic_cone
      [0, 128, 0], # trailer
      [255, 192, 203], # truck
      [128, 128, 128], # drivable_surface
      [165, 42, 42], # other flat
      [211, 211, 211], # sidewalk
      [34, 139, 34], # terrain
      [255, 215, 0], # manmade
      [173, 255, 47], # vegetation
    ]
  names:
    [
      "barrier",
      "bicycle",
      "bus",
      "car",
      "construction vehicle",
      "motorcycyle",
      "pedestrian",
      "traffic cone",
      "trailer",
      "truck",
      "driveable surface",
      "other flat",
      "sidewalk",
      "terrain",
      "manmade",
      "vegetation",
    ]
  fps: 2

semantic_kitti:
  colors: [
      [0, 0, 255], # car
      [0, 255, 255], # bicycle
      [255, 255, 0], # motorcycle
      [255, 192, 203], # truck
      [128, 0, 128], # other-vehicle
      [255, 0, 255], # person
      [0, 128, 128], # bicyclist
      [128, 128, 0], # motorcyclist
      [128, 128, 128], # road
      [255, 192, 203], # parking
      [211, 211, 211], # sidewalk
      [165, 42, 42], # other-ground
      [255, 215, 0], # building
      [255, 0, 0], # fence
      [173, 255, 47], # vegetation
      [160, 82, 45], # trunk
      [34, 139, 34], # terrain
      [112, 128, 144], # pole
      [220, 20, 60], # traffic-sign
    ]
  names:
    [
      "car",
      "bicycle",
      "motorcyle",
      "truck",
      "other vehicle",
      "person",
      "bicyclist",
      "motorcyclist",
      "road",
      "parking",
      "sidewalk",
      "other ground",
      "building",
      "fence",
      "vegetation",
      "trunk",
      "terrain",
      "pole",
      "traffic sign",
    ]
  fps: 10
